// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDHDbzianFmq3pOZGjcUoEGH1nNh_rJ-o',
    appId: '1:604040410806:android:3436eb791df06ffdd0d817',
    messagingSenderId: '604040410806',
    projectId: 'neu-spring2022-1',
    databaseURL: 'https://neu-spring2022-1-default-rtdb.firebaseio.com',
    storageBucket: 'neu-spring2022-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44Z9_14CC47bKpcv9Ac6q7NMopoz9_D8',
    appId: '1:604040410806:ios:d8975d9e315e5a35d0d817',
    messagingSenderId: '604040410806',
    projectId: 'neu-spring2022-1',
    databaseURL: 'https://neu-spring2022-1-default-rtdb.firebaseio.com',
    storageBucket: 'neu-spring2022-1.appspot.com',
    androidClientId: '604040410806-10tutoeehqqohpnbosg3e2s0du79tnfr.apps.googleusercontent.com',
    iosClientId: '604040410806-tj9rk0m1dk098tbfn6vo2p763colv8eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperGarageSaleApp',
  );
}
